'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HRM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property addmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property advsearchmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("advsearchmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deletemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deletemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downarrowmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downarrowmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fileimportmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileimportmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filtermat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filtermat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nextmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nextmat480() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextmat480", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prevmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prevmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prevmat480() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prevmat480", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reloadmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reloadmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property timermat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("timermat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usericon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("usericon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property usermat30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermat30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermat90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermat90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermat91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermat91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
